### ISSUE TITLE
Fails on large input files

### ISSUE THREAD

**Issue by kronicd** [AsteriskLabs/prenus#17]
```
$ ls -alFh
total 9896000
drwxr-xr-x   3 peter  staff    96B 31 Aug 09:07 ./
drwxr-xr-x+ 21 peter  staff   672B 31 Aug 09:10 ../
-rw-rw-rw-@  1 peter  staff   4.7G 31 Aug 09:00 a.nessus

$ prenus -o s0-r7 a.nessus -s0
/Users/peter/hax_shared/tools/prenus/lib/gemcache/ruby-nessus/ruby-nessus/parse.rb:17:in `read': Invalid argument @ io_fread - a.nessus (Errno::EINVAL)
	from lib/gemcache/ruby-nessus/ruby-nessus/parse.rb:17:in `initialize'
	from lib/input/nessusin.rb:37:in `new'
	from lib/input/nessusin.rb:37:in `block in import_nessus_files'
	from lib/input/nessusin.rb:35:in `each'
	from lib/input/nessusin.rb:35:in `import_nessus_files'
	from bin/prenus:160:in `<main>'
```

:(

**Comment by kronicd** [comment]
So it turns out ruby itself has issues reading files above 4.something GB.

You can work around by monkey patching ruby-nessus:


ruby-nessus/parse.rb
```
doc = file ? File.read(file) : options[:xml]

to

      dirname = File.dirname(file)
      `split -b 1024m #{file} #{file}.parts.`
      Dir.chdir(dirname)
      parts = Dir["#{file}.parts.*"]
      doc = ''
      parts.each do |partname|
        doc += File.read(partname)
        File.delete(partname)
      end```
